# Generated by Django 5.0.1 on 2024-01-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_auto_park'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='auto_park',
            new_name='auto_parks',
        ),
    ]
