# Generated by Django 5.0.1 on 2024-01-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_number_of_seats_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
    ]
