# Generated by Django 5.0.1 on 2024-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_carmodel_auto_parks'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
