# Generated by Django 5.0.1 on 2024-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carmodel_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='auto_parks',
        ),
    ]
