# Generated by Django 5.0.1 on 2024-02-08 09:10

from django.db import migrations, models

import core.services.upload_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_carmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar.upload_avatar),
        ),
    ]
